const resList2 = [
    {
        id: "210945",
        name: "Royal Restaurant",
        cloudinaryImageId: "https://imgs.search.brave.com/_X1lgttfUH9-62S2pQxDoaa5EmgPN5xxPd7PjaBwWwo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9yZXMu/Y2xvdWRpbmFyeS5j/b20vdGhlLWluZmF0/dWF0aW9uL2ltYWdl/L3VwbG9hZC9jX2Zp/bGwsd18zODQwLGFy/XzQ6MyxnX2NlbnRl/cixmX2F1dG8vaW1h/Z2VzL0JvbWJheV9C/cmFzc2VyaWVfT3Zl/cmhlYWRfRGlzaGVz/X0NyZWRpdF9WYW5l/c3NhX0xlbnRpbmVf/UGhvdG9ncmFwaHlf/YmJwZG1q.jpeg",
        locality: "Shivaji Nagar",
        areaName: "Central Bangalore",
        costForTwo: "₹300 for two",
        cuisines: ["Chinese", "Tandoor"],
        avgRating: 4.1,
        sla: {
            deliveryTime: 33,
            lastMileTravel: 2.6,
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "3.7 ★",
            subHeader: "921 ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432141",
        name: "The Spice Route",
        cloudinaryImageId: "https://imgs.search.brave.com/ddLXYlqx0Zhy58_N1GcEEDjGX3kpxPnoiwozNb0gHOA/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9kZW52/ZXJzcGljZXJvb20u/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzA5L0N1cnJ5/LmpwZw",
        locality: "Koramangala 5th Block",
        areaName: "Koramangala",
        costForTwo: "₹400 for two",
        cuisines: ["North Indian", "Chinese", "Continental"],
        avgRating: 4.3,
        parentId: "2896",
        avgRatingString: "4.3",
        totalRatingsString: "2.5K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 30,
            lastMileTravel: 3.4,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "3.4 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.3 ★",
            subHeader: "2.5K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432142",
        name: "The Foodie Hub",
        cloudinaryImageId: "https://imgs.search.brave.com/3Fhy3tjj1rpG3AI2wLl6bdEJFzfcZi2NUE9-zxelqXI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9odWJz/cmVzdGF1cmFudC5j/b20vYXNzZXRzL2lt/Zy9mb29kL2J1cmdl/cl9hbmRfZnJpZXMu/anBn",
        locality: "HSR Layout",
        areaName: "HSR Layout",
        costForTwo: "₹350 for two",
        cuisines: ["North Indian", "Chinese", "Italian"],
        avgRating: 4.2,
        parentId: "2896",
        avgRatingString: "4.2",
        totalRatingsString: "1.5K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 32,
            lastMileTravel: 4.2,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "4.2 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.2 ★",
            subHeader: "1.5K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432143",
        name: "Biryani Blues",
        cloudinaryImageId: "https://imgs.search.brave.com/3Ds6UtotRYX_YI4wzJKxHSswA2aJ1MUQy2qY9vtwSZ0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50LmpkbWFnaWNi/b3guY29tL2NvbXAv/YmFuZ2Fsb3JlL3A0/LzA4MHB4eDgwLnh4/ODAuMjIwODAxMjE0/MTMwLnc2cDQvY2F0/YWxvZ3VlL2Jpcnlh/bmktYmx1ZXMtaW5k/aXJhbmFnYXItYmFu/Z2Fsb3JlLWJpcnlh/bmktZGVsaXZlcnkt/cmVzdGF1cmFudHMt/eHNtY3ZncDhkcS5q/cGc_Y2xyPSMwMDY2/NjY",
        locality: "Koramangala 1st Block",
        areaName: "Koramangala",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Hyderabadi", "Indian"],
        avgRating: 4.1,
        parentId: "2896",
        avgRatingString: "4.1",
        totalRatingsString: "1.2K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 28,
            lastMileTravel: 2.9,
            serviceability: "SERVICEABLE",
            slaString: "25-30 mins",
            lastMileTravelString: "2.9 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.1 ★",
            subHeader: "1.2K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432144",
        name: "The Biryani Life",
        cloudinaryImageId: "https://imgs.search.brave.com/TZ8cAqnbak9CSXzJ3IffgVD2ff4RtFzu5SsMk6qapJg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbTEu/ZGluZW91dC5jby5p/bi9pbWFnZXMvdXBs/b2Fkcy9yZXN0YXVy/YW50L3NoYXJwZW4v/MS9lL3IvcDExMjYt/MTQ5MTIxMTg4MzU4/ZTIxNjZiOWY2YjIu/anBnP3RyPXRyOm4t/bWVkaXVt",
        locality: "Electronic City",
        areaName: "Electronic City",
        costForTwo: "₹400 for two",
        cuisines: ["Biryani", "Hyderabadi", "Indian"],
        avgRating: 4.3,
        parentId: "2896",
        avgRatingString: "4.3",
        totalRatingsString: "2.5K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 35,
            lastMileTravel: 5.1,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "5.1 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.3 ★",
            subHeader: "2.5K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432145",
        name: "Chinese Wok",
        cloudinaryImageId: "https://imgs.search.brave.com/l2iQDUyh7CKeNDgTceCfAjYNeJg-LrzASqGmw8BZVXg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y2hpbmF3b2tvci5j/b20vd3AtY29udGVu/dC91cGxvYWRzL2No/aW5hd29rb3IuY29t/LzIwMjMvMDMvd29u/dG9uLW5vb2RsZS1z/b3VwLTE0LmpwZw",
        locality: "Koramangala 5th Block",
        areaName: "Koramangala",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese", "Asian"],
        avgRating: 4.2,
        parentId: "2896",
        avgRatingString: "4.2",
        totalRatingsString: "1.5K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 25,
            lastMileTravel: 2.5,
            serviceability: "SERVICEABLE",
            slaString: "20-25 mins",
            lastMileTravelString: "2.5 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.2 ★",
            subHeader: "1.5K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    {
        id: "432147",
        name: "The Chinese Story",
        cloudinaryImageId: "https://imgs.search.brave.com/oBCqnW-I9zCIKOvOkzgrjfwnVGJx7pmoxk8DauVtCCw/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS50aW1lb3V0LmNv/bS9pbWFnZXMvMTAz/MDc1MzE5Lzc1MC80/MjIvaW1hZ2UuanBn",
        locality: "Koramangala 1st Block",
        areaName: "Koramangala",
        costForTwo: "₹400 for two",
        cuisines: ["Chinese", "Asian"],
        avgRating: 4.4,
        parentId: "2896",
        avgRatingString: "4.4",
        totalRatingsString: "2.5K+",
        promoted: false,
        adTrackingId: "",
        sla: {
            deliveryTime: 20,
            lastMileTravel: 2.1,
            serviceability: "SERVICEABLE",
            slaString: "15-20 mins",
            lastMileTravelString: "2.1 km",
            iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
            nextCloseTime: "2024-09-13 00:00:00",
            opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
            entityBadges: {
                textExtendedBadges: {},
                textBased: {},
                imageBased: {},
            },
        },
        aggregatedDiscountInfoV3: {
            header: "4.4 ★",
            subHeader: "2.5K+ ratings",
        },
        ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    },
    // More restaurant objects...
];
const resList = [
    {
        id: "1",
        name: "Spice Junction",
        dish: "Masala Dosa",
        cuisine: "South Indian",
        address: "123 Maple St, Bangalore",
        rating: 4.5,
        priceRange: "$$",
        deliveryTime: "30 mins",
        contact: "080 1234 5678",
        website: "www.spicejunction.com"
    },
    {
        id: "2",
        name: "Sushi House",
        dish: "California Roll",
        cuisine: "Japanese",
        address: "456 Oak Rd, Tokyo",
        rating: 4.7,
        priceRange: "$$$",
        deliveryTime: "40 mins",
        contact: "045 9876 5432",
        website: "www.sushihouse.jp"
    },
    {
        id: "3",
        name: "Pizza Haven",
        dish: "Margherita Pizza",
        cuisine: "Italian",
        address: "789 Elm Ave, Rome",
        rating: 4.3,
        priceRange: "$$",
        deliveryTime: "25 mins",
        contact: "06 8765 4321",
        website: "www.pizzahaven.it"
    },
    {
        id: "4",
        name: "Taco Fiesta",
        dish: "Chicken Tacos",
        cuisine: "Mexican",
        address: "321 Cedar St, Mexico City",
        rating: 4.6,
        priceRange: "$",
        deliveryTime: "20 mins",
        contact: "052 1234 5678",
        website: "www.tacofiesta.mx"
    },
    {
        id: "5",
        name: "Burger Point",
        dish: "Cheeseburger",
        cuisine: "American",
        address: "654 Pine Ln, New York",
        rating: 4.4,
        priceRange: "$",
        deliveryTime: "15 mins",
        contact: "212 8765 4321",
        website: "www.burgerpoint.com"
    },
    {
        id: "6",
        name: "Dragon Delight",
        dish: "Kung Pao Chicken",
        cuisine: "Chinese",
        address: "987 Birch Ave, Beijing",
        rating: 4.1,
        priceRange: "$$",
        deliveryTime: "35 mins",
        contact: "010 6543 2109",
        website: "www.dragondelight.cn"
    },
    {
        id: "7",
        name: "Le Petit Cafe",
        dish: "Croissant",
        cuisine: "French",
        address: "123 Rue de Paris, Paris",
        rating: 4.8,
        priceRange: "$$$",
        deliveryTime: "45 mins",
        contact: "+33 1 2345 6789",
        website: "www.lepetitcafe.fr"
    },
    {
        id: "8",
        name: "Biryani Palace",
        dish: "Hyderabadi Biryani",
        cuisine: "Indian",
        address: "456 Nizami St, Hyderabad",
        rating: 4.9,
        priceRange: "$$",
        deliveryTime: "30 mins",
        contact: "040 9876 5432",
        website: "www.biryanipalace.in"
    },
    {
        id: "9",
        name: "Greek Taverna",
        dish: "Gyro Plate",
        cuisine: "Greek",
        address: "789 Acropolis Rd, Athens",
        rating: 4.3,
        priceRange: "$$",
        deliveryTime: "30 mins",
        contact: "+30 21 2345 6789",
        website: "www.greektaverna.gr"
    },
    {
        id: "10",
        name: "Thai Spice",
        dish: "Pad Thai",
        cuisine: "Thai",
        address: "321 Lotus St, Bangkok",
        rating: 4.4,
        priceRange: "$$",
        deliveryTime: "25 mins",
        contact: "+66 2 9876 5432",
        website: "www.thaispice.co.th"
    },
    {
        id: "11",
        name: "Falafel Corner",
        dish: "Falafel Wrap",
        cuisine: "Middle Eastern",
        address: "654 Cedar St, Dubai",
        rating: 4.5,
        priceRange: "$",
        deliveryTime: "20 mins",
        contact: "+971 4 1234 5678",
        website: "www.falafelcorner.ae"
    },
    {
        id: "12",
        name: "BBQ Nation",
        dish: "Smoked Ribs",
        cuisine: "American",
        address: "987 BBQ Blvd, Dallas",
        rating: 4.2,
        priceRange: "$$$",
        deliveryTime: "40 mins",
        contact: "214 9876 5432",
        website: "www.bbqnation.com"
    }
];
export default resList2;